openapi: '3.0.3'
info:
  title: 'Calculator API'
  version: '1.0.0'
tags:
  - name: health
    description: Health check
  - name: calculator
    description: Calculator operations
externalDocs:
  url: https://www.youtube.com/@NerdiCoda
  description: My calculator documentation

servers:
  - url: http://{server_url}:{port}/api
    variables:
      server_url:
        default: localhost
      port:
        enum:
         - '4003'
         - '2000'
        default: '3000'
    description: This is my calculator server